### PR TITLE
Changed QVariantMap to QMultiMap

### LINKED ISSUE #269: QMap::unite deprecated and removed
**OS:**
MacOS Mojave 10.14.6

**Boomerang version or git hash:**
boomerang-cli v0.5.2-366-g1944b804e

**Steps to reproduce:**
1. Run the MacOS installation steps. 

**Expected behaviour/output:**
The application builds.

**Actual behaviour/output:**
You will get an error message during the build process:
```
/boomerang/src/boomerang/db/binary/BinarySection.cpp:26:19: error: 'unite' is deprecated: Use QMultiMap for maps storing multiple values with the same key.
      [-Werror,-Wdeprecated-declarations]
        val = val.unite(other.val);
                  ^
```
(The message is in line 26 and line 91 in the same file.)

**Additional comments:**
Apparently, HomeBrew upgraded to a Qt version (5.15.1) that removed the `unite` method from `QMap`. It has been deprecated for a while, so that's expected.

### PR DESCRIPTION
**Pull request by greg-szabo**
Fix #269 : QMap::unite deprecated and removed

This is a quick fix for the deprecated method in Qt. It compiles with Qt 5.15.1 (tested on OSX).
Seasoned C++ developers should take a look at it before merging. It is good enough if you need a compiled binary right now, but there might be better ways to deal with the issue.

### CODE REVIEW

**Comment by ceeac** [comment]
I cherry-picked the commit for #271 since the old CI builds are broken. Thanks for your contribution!
